### ISSUE TITLE
Rewrite into other language

### ISSUE THREAD

**Issue by bmusin** [rakudup/rakudup.github.io#3]
Hi.
No offence, but
don't you consider rewriting script in other language?
It's already ugly (because sh), and most probably will become unmanageable as it becomes bigger.
Best wishes, thanks.

**Comment by stmuk** [comment]
It's written in shell exactly because I want to discourage it becoming much bigger and it seems the right tool for this sort of task of bootstrapping a language. I don't regard shell as particularly uglier than anything else. I've considered rewriting in perl 5 (since the rakudo build is dependent on that anyway) but I'm in no hurry to do this. Using anything other than perl 5 or shell would seem silly.
